version: "2"         # required to adjust maintainability checks

## Excluding some items from CodeClimate
## - Client Directory: Contains SemanticUI Code
## - Tests Directory: Ignore tests
exclude_patterns:
- "client/"
- "tests/"

## Adjust default checks configuration
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 200
  return-statements:
    config:
      threshold: 4
